version: '3'
services:
  web-application:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.web-application
    volumes:
      - ./Web-Application:/var/www/html
    working_dir: /var/www/html
    environment:
      DB_HOST: "${PLAYBOOK_SERVER_DB_HOST}"
      DB_USERNAME: "${PLAYBOOK_SERVER_DB_USERNAME}"
      DB_PASSWORD: "${PLAYBOOK_SERVER_DB_PASSWORD}"
      DB_NAME: "${PLAYBOOK_SERVER_DB_NAME}"
      PLAYBOOK_NOTIFIER_HOST: "${PLAYBOOK_NOTIFIER_HOST}"
      PLAYBOOK_NOTIFIER_PORT: "${PLAYBOOK_NOTIFIER_PORT}"
    ports:
      - '8080:80'
  playbook-server:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.playbook-server
    volumes:
      - ./playbook_server:/app
    working_dir: /app
    command:
      - php
      - -S
      - 0.0.0.0:8080
    environment:
      DB_HOST: "${PLAYBOOK_SERVER_DB_HOST}"
      DB_USERNAME: "${PLAYBOOK_SERVER_DB_USERNAME}"
      DB_PASSWORD: "${PLAYBOOK_SERVER_DB_PASSWORD}"
      DB_NAME: "${PLAYBOOK_SERVER_DB_NAME}"
    ports:
      - '9002:8080'
  playbook-notifier:
    image: node:alpine
    volumes:
      - ./dockerfiles/node-wrapper.sh:/node-wrapper.sh
      - ./playbook-notifier:/app
    working_dir: /app
    command:
      - /node-wrapper.sh
    ports:
      - "${PLAYBOOK_NOTIFIER_PORT}:8080"
  treasurehunt-server:
    image: node:alpine
    volumes:
      - ./dockerfiles/node-wrapper.sh:/node-wrapper.sh
      - ./treasurehunt_server:/app
    working_dir: /app
    command:
      - /node-wrapper.sh
    ports:
      - '9000:8080'
  mysql:
    image: mysql:latest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}" 
    ports:
      - '3306:3306'
