version: '3'
services:
  web-application:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.web-application
    volumes:
      - ./Web-Application:/var/www/html
    working_dir: /var/www/html
    environment:
      DB_HOST: "${PLAYBOOK_SERVER_DB_HOST}"
      DB_USERNAME: "${PLAYBOOK_SERVER_DB_USERNAME}"
      DB_PASSWORD: "${PLAYBOOK_SERVER_DB_PASSWORD}"
      DB_NAME: "${PLAYBOOK_SERVER_DB_NAME}"
      PLAYBOOK_NOTIFIER_HOST: "${PLAYBOOK_NOTIFIER_HOST}"
      PLAYBOOK_NOTIFIER_PORT: "${PLAYBOOK_NOTIFIER_PORT}"
      TREASUREHUNT_1_HOST: "${TREASUREHUNT_1_HOST}"
      TREASUREHUNT_1_PORT: "${TREASUREHUNT_1_PORT}"
      TREASUREHUNT_2_HOST: "${TREASUREHUNT_2_HOST}"
      TREASUREHUNT_2_PORT: "${TREASUREHUNT_2_PORT}"
      LEADERBOARD_HOST: "${LEADERBOARD_HOST}"
      LEADERBOARD_PORT: "${LEADERBOARD_PORT}"
    ports:
      - '${OPERATOR_PORT}:80'
  playbook-server:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.playbook-server
    volumes:
      - ./dockerfiles/php-wrapper.sh:/php-wrapper.sh
      - ./playbook_server:/app
    working_dir: /app
    command:
      - /php-wrapper.sh
    environment:
      DB_DSN: "mysql:host=${PLAYBOOK_SERVER_DB_HOST};dbname=${PLAYBOOK_SERVER_DB_NAME};charset=utf8"
      DB_USERNAME: "${PLAYBOOK_SERVER_DB_USERNAME}"
      DB_PASSWORD: "${PLAYBOOK_SERVER_DB_PASSWORD}"
    ports:
      - '${PLAYBOOK_SERVER_PORT}:9000'
  playbook-notifier:
    image: node:alpine
    volumes:
      - ./dockerfiles/node-wrapper.sh:/node-wrapper.sh
      - ./playbook-notifier:/app
    working_dir: /app
    command:
      - /node-wrapper.sh
    environment:
      GCM_KEY: "${PLAYBOOK_NOTIFIER_GCM_KEY}"
    ports:
      - "${PLAYBOOK_NOTIFIER_PORT}:8080"
  treasurehunt-server-1:
    image: node:alpine
    volumes:
      - ./dockerfiles/node-wrapper.sh:/node-wrapper.sh
      - ./treasurehunt_server:/app
    working_dir: /app
    command:
      - /node-wrapper.sh
    ports:
      - '${TREASUREHUNT_1_PORT}:8080'
  treasurehunt-server-2:
    image: node:alpine
    volumes:
      - ./dockerfiles/node-wrapper.sh:/node-wrapper.sh
      - ./treasurehunt_server:/app
    working_dir: /app
    command:
      - /node-wrapper.sh
    ports:
      - '${TREASUREHUNT_2_PORT}:8080'
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}" 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - '${PHPMYADMIN_PORT}:80'
